### ISSUE TITLE
Dynamic placeholders support

### ISSUE THREAD

**Issue by asmagin** [asmagin/sitecore-js-presentation#6]

**Comment by yannisgu** [comment]
How do you plan to support this?
I see different possibillities:
* Add JS function getDynamicPlaceholders with the same signature as getPlaceholders
* getPlaceholders returns an array of objects instead of strings: `[{'key': 'placeholderKey', 'dynamic': true}]`
* Treat every placeholder inside a rendering as dynamic placeholder

**Comment by asmagin** [comment]
@yannisgu What about this approach: http://www.sitecorenutsbolts.net/2016/08/02/Sitecore-React-a-new-Sitecore-module/

You could treat placeholders that are prepended with **$id** as Dynamic
